/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'AgentDetails'
    ],
    views: [
        'TabPanel',
        'NavigationPanel',
        'MyQueuesPanel',
        'SearchPanel'
    ],
    autoCreateViewport: true,
    controllers: [
        'AgentController',
        'LoginController',
        'HeaderController',
        'SecurityController'
    ],
    name: 'Spm',

    launch: function() {
        Spm.application = this;
        this.addEvents('startAuthentication');
        this.fireEvent('startAuthentication');

        var login = Ext.create('Spm.view.LoginWindow');
        login.hide();
    }

});
