/*
 * File: app/model/Agent.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.model.Agent', {
    extend: 'Ext.data.Model',
    alias: 'model.agent',

    uses: [
        'Spm.model.AgentDetails'
    ],

    fields: [
        {
            name: 'code'
        },
        {
            name: 'availability'
        },
        {
            name: 'activeCount'
        },
        {
            name: 'heldCount'
        }
    ],

    hasOne: {
        associationKey: 'details',
        model: 'Spm.model.AgentDetails',
        getterName: 'details'
    },

    isAvailable: function() {
        return this.get('availability') == 'Available';
    },

    toggleAvailability: function() {
        var currentAvailability = this.get('availability');
        this.set('availability', !currentAvailability);
        return this.get('availability');
    }

});