/*
 * File: app/store/QueueStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.store.QueueStore', {
    extend: 'Ext.data.Store',
    alias: 'store.queueStore',

    requires: [
        'Spm.model.Queue'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'Spm.model.Queue',
            sortOnLoad: false,
            storeId: 'queueStore',
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json',
                    root: 'agent.queues'
                }
            },
            listeners: {
                datachanged: {
                    fn: me.onJsonstoreDataChangeD,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreDataChangeD: function(store, eOpts) {
        console.log('dataChanged');
    }

});