
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext": "../../ext/src",
  "Spm": "../../app",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.BoxReorderer": [],
  "Spm.view.AgentStatusPanel": [],
  "Spm.view.NavigationPanel": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Spm.view.SpmViewport": [],
  "Ext.ux.FieldReplicator": [],
  "Spm.controller.QueueController": [],
  "Spm.model.Agent": [],
  "Spm.controller.LoginController": [],
  "Spm.view.AppContainer": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Spm.view.LoginWindow": [],
  "Spm.view.QueueContainer": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Spm.view.HeaderView": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Spm.store.QueueStore": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Spm.controller.TabController": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.PreviewPlugin": [],
  "Spm.view.SearchPanel": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.controller.SecurityController": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Spm.model.Queue": [],
  "Spm.controller.AgentController": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Spm.view.TabPanel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Spm.view.Viewport": [],
  "Spm.view.MyQueuesPanel": [],
  "Ext.ux.TabScrollerMenu": [],
  "Spm.proxy.SpmAjaxProxy": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Spm.mixin.TabHeaderId": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Spm.store.AuthenticatedAgent": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ]
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.BoxReorderer": [],
  "Spm.view.AgentStatusPanel": [
    "widget.agentStatusPanel"
  ],
  "Spm.view.NavigationPanel": [
    "widget.navigationPanel"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Spm.view.SpmViewport": [
    "widget.spmViewport"
  ],
  "Ext.ux.FieldReplicator": [],
  "Spm.controller.QueueController": [
    "controller.queueController"
  ],
  "Spm.model.Agent": [
    "model.agent"
  ],
  "Spm.controller.LoginController": [
    "controller.loginController"
  ],
  "Spm.view.AppContainer": [
    "widget.appContainer"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Spm.view.LoginWindow": [
    "widget.loginWindow"
  ],
  "Spm.view.QueueContainer": [
    "widget.queueContainer"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Spm.view.HeaderView": [
    "widget.headerView"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Ext.ux.DataView.DragSelector": [],
  "Spm.store.QueueStore": [
    "store.queueStore"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Spm.controller.TabController": [
    "controller.tabController"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Spm.view.SearchPanel": [
    "widget.searchPanel"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.controller.SecurityController": [
    "controller.securityController"
  ],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Spm.model.Queue": [
    "model.queue"
  ],
  "Spm.controller.AgentController": [
    "controller.agentController"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Spm.view.TabPanel": [
    "widget.tabPanel"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Spm.view.Viewport": [],
  "Spm.view.MyQueuesPanel": [
    "widget.myQueuesPanel"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Spm.proxy.SpmAjaxProxy": [
    "proxy.spmAjaxProxy"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Spm.mixin.TabHeaderId": [],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Spm.store.AuthenticatedAgent": [
    "store.authenticatedAgent"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ]
});
