
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext": "../../ext/src",
  "Spm": "../../app",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.BoxReorderer": [],
  "Spm.view.AgentStatusPanel": [],
  "Spm.store.ServiceProblems": [],
  "Spm.view.NavigationPanel": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Spm.controller.Security": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Spm.store.AllQueues": [],
  "Spm.controller.Queues": [],
  "Spm.view.SpmViewport": [],
  "Ext.ux.FieldReplicator": [],
  "Spm.model.Agent": [],
  "Spm.view.AppContainer": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Spm.view.LoginWindow": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Spm.view.QueueTabToolbar": [],
  "Spm.view.HeaderView": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Spm.model.ServiceProblem": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Spm.model.WorkItem": [],
  "Spm.controller.Login": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.PreviewPlugin": [],
  "Spm.view.QueueTabContent": [],
  "Spm.view.SearchPanel": [],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Spm.view.StandardDialog": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Spm.store.AgentQueues": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.domain.ProxyEventDomain": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Spm.model.Queue": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.ToolbarDroppable": [],
  "Spm.controller.Errors": [],
  "Ext.ux.event.Maker": [],
  "Spm.view.Viewport": [],
  "Spm.view.MyQueuesPanel": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.DataView.Draggable": [],
  "Spm.controller.MyQueues": [],
  "Ext.ux.TabCloseMenu": [],
  "Spm.view.BulkTransferDialog": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.TreePicker": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Spm.store.AuthenticatedAgent": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Spm.controller.MyStatus": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.BoxReorderer": [],
  "Spm.view.AgentStatusPanel": [
    "widget.agentStatusPanel"
  ],
  "Spm.store.ServiceProblems": [
    "store.serviceProblems"
  ],
  "Spm.view.NavigationPanel": [
    "widget.navigationPanel"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Spm.controller.Security": [
    "controller.security"
  ],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Spm.store.AllQueues": [
    "store.allQueues"
  ],
  "Spm.controller.Queues": [
    "controller.queues"
  ],
  "Spm.view.SpmViewport": [
    "widget.spmViewport"
  ],
  "Ext.ux.FieldReplicator": [],
  "Spm.model.Agent": [
    "model.agent"
  ],
  "Spm.view.AppContainer": [
    "widget.appContainer"
  ],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Spm.view.LoginWindow": [
    "widget.loginWindow"
  ],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Spm.view.QueueTabToolbar": [
    "widget.queueTabToolbar"
  ],
  "Spm.view.HeaderView": [
    "widget.headerView"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Spm.model.ServiceProblem": [
    "model.serviceProblem"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Spm.model.WorkItem": [
    "model.workItem"
  ],
  "Spm.controller.Login": [
    "controller.login"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Spm.view.QueueTabContent": [
    "widget.queueTabContent"
  ],
  "Spm.view.SearchPanel": [
    "widget.searchPanel"
  ],
  "Ext.ux.DataView.Animated": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Spm.view.StandardDialog": [
    "widget.standardDialog"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Spm.store.AgentQueues": [
    "store.agentQueues"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.domain.ProxyEventDomain": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Recorder": [],
  "Ext.ux.event.Player": [],
  "Ext.ux.ajax.SimManager": [],
  "Spm.model.Queue": [
    "model.queue"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Spm.controller.Errors": [
    "controller.errors"
  ],
  "Ext.ux.event.Maker": [],
  "Spm.view.Viewport": [],
  "Spm.view.MyQueuesPanel": [
    "widget.myQueuesPanel"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Spm.controller.MyQueues": [
    "controller.myQueues"
  ],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Spm.view.BulkTransferDialog": [
    "widget.bulkTransferDialog"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Spm.store.AuthenticatedAgent": [
    "store.authenticatedAgent"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Spm.controller.MyStatus": [
    "controller.myStatus"
  ]
});
