/*
 * File: app/controller/AgentController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.controller.AgentController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.agentController',

    isAvailable: false,
    stores: [
        'AuthenticatedAgent'
    ],
    views: [
        'MyStatusPanel'
    ],

    refs: [
        {
            ref: 'agentStateLabel',
            selector: 'label#agentStateLabel'
        },
        {
            ref: 'spmViewport',
            selector: 'viewport#spmViewport'
        }
    ],

    onMakeMeAvailable: function(button, e, eOpts) {
        var label = this.getAgentStateLabel();

        if(this.isAvailable) {
            label.setText("Unavailable");
            label.removeCls("availability-indicator-on");
            label.addCls("availability-indicator-off");
        } else {
            label.setText("Available");
            label.removeCls("availability-indicator-off");
            label.addCls("availability-indicator-on");

        }    
        this.isAvailable = !this.isAvailable;

    },

    onAgentLogin: function(button, e, eOpts) {
        this.getSpmViewport().showMainContainer();


        Ext.Ajax.request({
            url: '/j_spring_security_check',
            params: {
                'j_username': "foo",
                'j_password': "bah"
            }

        });
    },

    onLaunch: function() {
        this.getSpmViewport().showLoginDialog();
    },

    init: function(application) {
        this.control({
            "button#makeMeAvailableButton": {
                click: this.onMakeMeAvailable
            },
            "button#loginButton": {
                click: this.onAgentLogin
            }
        });
    }

});
