/*
 * File: app/controller/HeaderController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.controller.HeaderController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.headerController',

    models: [
        'Agent'
    ],
    stores: [
        'AuthenticatedAgent'
    ],
    views: [
        'HeaderContainer'
    ],

    refs: [
        {
            ref: 'headerContainer',
            selector: 'headerContainer'
        }
    ],

    onAuthenticated: function() {
        var store = this.getAuthenticatedAgentStore();

        var agent = store.first();

        var headerView = this.getHeaderContainer();

        headerView.update({'name': agent.details().displayName()});
    },

    init: function(application) {
        application.on({
            authenticated: {
                fn: this.onAuthenticated,
                scope: this
            }
        });
    }

});
