/*
 * File: app/controller/LoginController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.controller.LoginController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.loginController',

    views: [
        'LoginForm'
    ],

    onSpecialKey: function(field, e, eOpts) {
        if(e.getKey() == e.ENTER) {
            this.doLogin(field.up('form').getForm());
        }
    },

    onLoginClick: function(button, e, eOpts) {
        this.doLogin(button.up('form').getForm());

    },

    onResetClick: function(button, e, eOpts) {
        button.up('form').getForm().reset();
    },

    doLogin: function(form) {
        if(form.isValid()) {
            Spm.application.fireEvent('performAuthentication', {'username': form.findField('username').getValue(), 'password': form.findField('password').getValue()});
        }
    },

    init: function(application) {
        this.control({
            "textfield": {
                specialkey: this.onSpecialKey
            },
            "button#login-button": {
                click: this.onLoginClick
            },
            "button#reset-button": {
                click: this.onResetClick
            }
        });
    }

});
