/*
 * File: app/controller/QueueController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.controller.QueueController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.queueController',

    mixins: [
        'Spm.mixin.TabHeaderId'
    ],
    requires: [
        'Spm.mixin.TabHeaderId'
    ],

    views: [
        'QueueContainer'
    ],

    constructor: function(cfg) {
        cfg = cfg || {};
        this.callParent(this.processQueueController(cfg));
    },

    processQueueController: function(config) {
        this.queue = config.queue;

        console.log(this.getApplication());
        console.log(Spm.application);

        return config;
    },

    tabView: function() {
        var items = [];
        var config = {};

        items.push(Ext.widget('queueContainer', {id: this.idFor(), queue: this.queue}));

        config.items = items;

        config.closable = true;
        config.title = this.queue.get('name');

        return config;
    },

    init: function(application) {
        console.log(selector);
        var selector = 'a#foo-'+this.queue.get('id');
        console.log(selector);
        this.control({
            selector: {
                click: this.onButtonClick
            }
        });
    },

    queueIdThing: function() {
        return 'queue-container-' + this.queue.get('id')
    },

    onButtonClick: function(button,e,eOpts) {
        console.log(button);
    }

});
