/*
 * File: app/controller/TabController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.controller.TabController', {
    extend: 'Ext.app.Controller',
    alias: 'controller.tabController',

    views: [
        'TabPanel'
    ],

    refs: [
        {
            ref: 'tabPanel',
            selector: '#tab-panel'
        }
    ],

    onQueueSelected: function(queue) {
        var tabPanel = this.getTabPanel();

        var tabHeaderId = this.tabHeaderIdFor(queue);
        var tabHeader = tabPanel.down('#' + tabHeaderId);

        if(!tabHeader) {
            var tabItem = Ext.create('Spm.view.QueueContainer', {id: tabHeaderId, closable: true, title: queue.get('name')});
            tabPanel.add(tabItem);
        }

        tabPanel.setActiveTab(tabHeaderId);
    },

    tabHeaderIdFor: function(queue) {
        return 'tab-header-queue-'+queue.get('id');
    },

    init: function(application) {
        application.on({
            queueSelected: {
                fn: this.onQueueSelected,
                scope: this
            }
        });
    }

});
