
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.ux.BoxReorderer": "../../ext/src/ux/BoxReorderer.js",
  "Ext.ux.CellDragDrop": "../../ext/src/ux/CellDragDrop.js",
  "Ext.ux.SlidingPager": "../../ext/src/ux/SlidingPager.js",
  "Ext.ux.GroupTabRenderer": "../../ext/src/ux/GroupTabRenderer.js",
  "Ext.ux.TabReorderer": "../../ext/src/ux/TabReorderer.js",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "Ext.ux.layout": "../../ext/src/ux/layout",
  "Ext.ux.FieldReplicator": "../../ext/src/ux/FieldReplicator.js",
  "Ext.ux.RowExpander": "../../ext/src/ux/RowExpander.js",
  "Ext.ux.data": "../../ext/src/ux/data",
  "Ext.ux.form": "../../ext/src/ux/form",
  "Ext": "../../ext/src",
  "Spm": "../../app",
  "Ext.ux": "../../app",
  "Ext.ux.ajax": "../../ext/src/ux/ajax",
  "Ext.ux.ToolbarDroppable": "../../ext/src/ux/ToolbarDroppable.js",
  "Ext.ux.event": "../../ext/src/ux/event",
  "Ext.ux.GMapPanel": "../../ext/src/ux/GMapPanel.js",
  "Ext.ux.TabScrollerMenu": "../../ext/src/ux/TabScrollerMenu.js",
  "Ext.ux.IFrame": "../../ext/src/ux/IFrame.js",
  "Ext.ux.TabCloseMenu": "../../ext/src/ux/TabCloseMenu.js",
  "Ext.ux.GroupTabPanel": "../../ext/src/ux/GroupTabPanel.js",
  "Ext.ux.LiveSearchGridPanel": "../../ext/src/ux/LiveSearchGridPanel.js",
  "Ext.ux.DataTip": "../../ext/src/ux/DataTip.js",
  "Ext.ux.dd": "../../ext/src/ux/dd",
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext.ux.TreePicker": "../../ext/src/ux/TreePicker.js",
  "Ext.ux.statusbar": "../../ext/src/ux/statusbar",
  "Ext.ux.PreviewPlugin": "../../ext/src/ux/PreviewPlugin.js",
  "Ext.ux.grid": "../../ext/src/ux/grid",
  "Ext.ux.Spotlight": "../../ext/src/ux/Spotlight.js",
  "Ext.ux.DataView": "../../ext/src/ux/DataView",
  "Ext.ux.ProgressBarPager": "../../ext/src/ux/ProgressBarPager.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Spm.store.AllQueues": [],
  "Spm.controller.action.queuedashboard.RefreshDashboardAction": [
    "Spm.action.RefreshDashboardAction"
  ],
  "Spm.model.Agent": [],
  "Spm.model.QueueDashboardEntry": [],
  "Spm.view.application.MyItemsTabContent": [],
  "Spm.view.queue.BulkTransferDialog": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.DataView.DragSelector": [],
  "Spm.view.navigation.MyQueuesPanel": [],
  "Spm.controller.Searches": [],
  "Spm.view.queuedashboard.QueueDashboardTabContent": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Spm.view.application.SpmViewport": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Spm.controller.action.ToggleAvailabilityAction": [
    "Spm.action.ToggleAvailabilityAction"
  ],
  "Spm.model.WorkItem": [],
  "Spm.view.component.StandardDialog": [],
  "Ext.ux.PreviewPlugin": [],
  "Spm.proxy.EventHistoryApiProxy": [],
  "Spm.model.EventHistoryItem": [],
  "Spm.view.queue.ActionToolbar": [],
  "Spm.view.serviceproblem.WorkItemPanel": [],
  "Spm.view.queue.BulkClearDialog": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Spm.controller.action.queue.BulkTransferAction": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Spm.view.queue.QueueTabContent": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.event.Recorder": [],
  "Spm.view.application.LoginDialog": [],
  "Spm.controller.mixins.ActionContextManager": [],
  "Spm.controller.action.serviceproblem.PullServiceProblemAction": [
    "Spm.action.PullServiceProblemAction"
  ],
  "Ext.ux.ajax.SimManager": [],
  "Spm.controller.mixins.RegisteredActions": [],
  "Spm.model.Queue": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Spm.controller.Errors": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Spm.store.EventHistory": [],
  "Spm.controller.action.serviceproblem.RefreshAction": [
    "Spm.action.RefreshAction"
  ],
  "Spm.view.component.ActionDialog": [],
  "Spm.controller.action.serviceproblem.AddNoteAction": [
    "Spm.action.AddNoteAction"
  ],
  "Spm.view.search.SearchResultTabContent": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "Spm.controller.action.serviceproblem.HoldAndReleaseWorkItemAction": [
    "Spm.action.HoldAndReleaseWorkItemAction"
  ],
  "Spm.store.AuthenticatedAgent": [],
  "Spm.view.serviceproblem.ServiceProblemTabContent": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "Ext.ux.BoxReorderer": [],
  "Spm.store.ServiceProblems": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Spm.proxy.AgentStateApiProxy": [],
  "Spm.view.application.AppContainer": [],
  "Spm.controller.Security": [],
  "Spm.view.component.Notification": [
    "Spm.component.Notification"
  ],
  "Spm.view.serviceproblem.ActionToolbar": [],
  "Spm.controller.Queues": [],
  "Spm.proxy.ServiceProblemApiProxy": [],
  "Ext.ux.FieldReplicator": [],
  "Spm.controller.action.serviceproblem.RefreshEventHistoryAction": [
    "Spm.action.RefreshEventHistoryAction"
  ],
  "Ext.ux.grid.filter.ListFilter": [],
  "Spm.view.component.AssociationCapableForm": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Spm.controller.MyItems": [],
  "Spm.proxy.ApiProxy": [],
  "Spm.view.application.HeaderView": [],
  "Spm.model.ServiceProblem": [],
  "Spm.view.queuedashboard.ActionToolbar": [],
  "Spm.store.QueueDashboardEntries": [],
  "Ext.ux.GMapPanel": [],
  "Spm.controller.action.BaseAction": [],
  "Spm.controller.mixins.ServiceProblemClickHandler": [],
  "Spm.model.AgentState": [],
  "Spm.view.serviceproblem.EventHistoryPanel": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Spm.controller.action.queue.BulkClearAction": [],
  "Spm.overrides.AbstractStore": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Spm.view.navigation.AgentStatusPanel": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Spm.view.serviceproblem.eventhistory.ActionToolbar": [],
  "Ext.ux.layout.Center": [],
  "Ext.ux.DataView.Animated": [],
  "Spm.view.serviceproblem.ServiceProblemPanel": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Spm.view.renderer.NestedPropertyRenderer": [],
  "Spm.controller.action.queue.BaseBulkAction": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.store.AgentQueues": [],
  "Ext.ux.RowExpander": [],
  "Spm.domain.ProxyEventDomain": [],
  "Ext.ux.event.Player": [],
  "Spm.controller.action.SearchAction": [
    "Spm.action.SearchAction"
  ],
  "Spm.view.navigation.SearchPanel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.window.Notification": [],
  "Spm.store.AgentState": [],
  "Ext.ux.DataView.Draggable": [],
  "Spm.controller.MyQueues": [],
  "Spm.proxy.QueueDashboardEntryApiProxy": [],
  "Ext.ux.TabCloseMenu": [],
  "Spm.controller.ServiceProblems": [],
  "Spm.proxy.ApiOperation": [],
  "Spm.controller.AgentStatus": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Spm.controller.mixins.IsActionContext": [],
  "Spm.view.navigation.NavigationPanel": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "Spm.controller.QueueDashboard": [],
  "Spm.view.serviceproblem.eventhistory.AddNoteDialog": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Spm.store.AllQueues": [
    "store.allQueues"
  ],
  "Spm.controller.action.queuedashboard.RefreshDashboardAction": [],
  "Spm.model.Agent": [
    "model.agent"
  ],
  "Spm.model.QueueDashboardEntry": [
    "model.queueDashboardEntry"
  ],
  "Spm.view.application.MyItemsTabContent": [
    "widget.myItemsTabContent"
  ],
  "Spm.view.queue.BulkTransferDialog": [
    "widget.bulkTransferDialog"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Spm.view.navigation.MyQueuesPanel": [
    "widget.myQueuesPanel"
  ],
  "Spm.controller.Searches": [
    "controller.searches"
  ],
  "Spm.view.queuedashboard.QueueDashboardTabContent": [
    "widget.queueDashboard"
  ],
  "Ext.ux.grid.menu.ListMenu": [],
  "Spm.view.application.SpmViewport": [
    "widget.spmViewport"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Spm.controller.action.ToggleAvailabilityAction": [],
  "Spm.model.WorkItem": [
    "model.workItem"
  ],
  "Spm.view.component.StandardDialog": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Spm.proxy.EventHistoryApiProxy": [],
  "Spm.model.EventHistoryItem": [
    "model.eventHistoryItem"
  ],
  "Spm.view.queue.ActionToolbar": [
    "widget.queueTabToolbar"
  ],
  "Spm.view.serviceproblem.WorkItemPanel": [
    "widget.workItemPanel"
  ],
  "Spm.view.queue.BulkClearDialog": [
    "widget.bulkClearDialog"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Spm.controller.action.queue.BulkTransferAction": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Spm.view.queue.QueueTabContent": [
    "widget.queueTabContent"
  ],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.event.Recorder": [],
  "Spm.view.application.LoginDialog": [
    "widget.loginDialog"
  ],
  "Spm.controller.mixins.ActionContextManager": [],
  "Spm.controller.action.serviceproblem.PullServiceProblemAction": [],
  "Ext.ux.ajax.SimManager": [],
  "Spm.controller.mixins.RegisteredActions": [],
  "Spm.model.Queue": [
    "model.queue"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Spm.controller.Errors": [
    "controller.errors"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Spm.store.EventHistory": [
    "store.eventHistory"
  ],
  "Spm.controller.action.serviceproblem.RefreshAction": [],
  "Spm.view.component.ActionDialog": [],
  "Spm.controller.action.serviceproblem.AddNoteAction": [],
  "Spm.view.search.SearchResultTabContent": [
    "widget.searchResultTabContent"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "Spm.controller.action.serviceproblem.HoldAndReleaseWorkItemAction": [],
  "Spm.store.AuthenticatedAgent": [
    "store.authenticatedAgent"
  ],
  "Spm.view.serviceproblem.ServiceProblemTabContent": [
    "widget.serviceProblemTabContent"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "Ext.ux.BoxReorderer": [],
  "Spm.store.ServiceProblems": [
    "store.serviceProblems"
  ],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Spm.proxy.AgentStateApiProxy": [],
  "Spm.view.application.AppContainer": [
    "widget.appContainer"
  ],
  "Spm.controller.Security": [
    "controller.security"
  ],
  "Spm.view.component.Notification": [],
  "Spm.view.serviceproblem.ActionToolbar": [
    "widget.serviceProblemTabToolbar"
  ],
  "Spm.controller.Queues": [
    "controller.queues"
  ],
  "Spm.proxy.ServiceProblemApiProxy": [],
  "Ext.ux.FieldReplicator": [],
  "Spm.controller.action.serviceproblem.RefreshEventHistoryAction": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Spm.view.component.AssociationCapableForm": [
    "widget.associationCapableForm"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "Spm.controller.MyItems": [
    "controller.myItems"
  ],
  "Spm.proxy.ApiProxy": [],
  "Spm.view.application.HeaderView": [
    "widget.headerView"
  ],
  "Spm.model.ServiceProblem": [
    "model.serviceProblem"
  ],
  "Spm.view.queuedashboard.ActionToolbar": [
    "widget.queueDashboardToolbar"
  ],
  "Spm.store.QueueDashboardEntries": [
    "store.queueDashboardEntries"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Spm.controller.action.BaseAction": [],
  "Spm.controller.mixins.ServiceProblemClickHandler": [],
  "Spm.model.AgentState": [
    "model.agentState"
  ],
  "Spm.view.serviceproblem.EventHistoryPanel": [
    "widget.eventHistoryPanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Spm.controller.action.queue.BulkClearAction": [],
  "Spm.overrides.AbstractStore": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Spm.view.navigation.AgentStatusPanel": [
    "widget.agentStatusPanel"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Spm.view.serviceproblem.eventhistory.ActionToolbar": [
    "widget.eventHistoryActionToolbar"
  ],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Ext.ux.DataView.Animated": [],
  "Spm.view.serviceproblem.ServiceProblemPanel": [
    "widget.serviceProblemPanel"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Spm.view.renderer.NestedPropertyRenderer": [],
  "Spm.controller.action.queue.BaseBulkAction": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Spm.store.AgentQueues": [
    "store.agentQueues"
  ],
  "Ext.ux.RowExpander": [],
  "Spm.domain.ProxyEventDomain": [],
  "Ext.ux.event.Player": [],
  "Spm.controller.action.SearchAction": [],
  "Spm.view.navigation.SearchPanel": [
    "widget.searchPanel"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "Ext.ux.window.Notification": [
    "widget.uxNotification"
  ],
  "Spm.store.AgentState": [
    "store.agentState"
  ],
  "Ext.ux.DataView.Draggable": [],
  "Spm.controller.MyQueues": [
    "controller.myQueues"
  ],
  "Spm.proxy.QueueDashboardEntryApiProxy": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Spm.controller.ServiceProblems": [
    "controller.serviceProblems"
  ],
  "Spm.proxy.ApiOperation": [],
  "Spm.controller.AgentStatus": [
    "controller.agentStatus"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Spm.controller.mixins.IsActionContext": [],
  "Spm.view.navigation.NavigationPanel": [
    "widget.navigationPanel"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "Spm.controller.QueueDashboard": [
    "controller.queueDashboard"
  ],
  "Spm.view.serviceproblem.eventhistory.AddNoteDialog": [
    "widget.addNoteDialog"
  ]
});
