/*
 * File: app/view/LoginWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.view.LoginWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.loginWindow',

    height: 127,
    width: 372,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Login',
    defaultFocus: 'usernameField',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 119,
                    width: 333,
                    bodyPadding: 10,
                    frameHeader: false,
                    header: false,
                    title: 'Login',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'username',
                            itemId: 'usernameField',
                            fieldLabel: 'Username:',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            id: 'password',
                            itemId: 'passwordField',
                            fieldLabel: 'Password:',
                            inputType: 'password',
                            allowBlank: false
                        },
                        {
                            xtype: 'container',
                            layout: {
                                pack: 'end',
                                padding: '',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'reset-button',
                                    text: 'Reset'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 5
                                },
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    disabled: true,
                                    id: 'login-button',
                                    text: 'Login'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});