/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginForm',

    height: 119,
    width: 333,
    bodyPadding: 10,
    title: 'Login',

    initComponent: function() {
        var me = this;

        me.addEvents(
            'startAuthentication'
        );

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'usernameField',
                    fieldLabel: 'Username:'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    itemId: 'passwordField',
                    fieldLabel: 'Password:',
                    inputType: 'password'
                },
                {
                    xtype: 'container',
                    layout: {
                        pack: 'end',
                        padding: '',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            text: 'Reset'
                        },
                        {
                            xtype: 'tbspacer',
                            width: 5
                        },
                        {
                            xtype: 'button',
                            itemId: 'loginButton',
                            text: 'Login'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});