/*
 * File: app/view/MyStatusPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.view.MyStatusPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.myStatusPanel',

    height: 126,
    margin: '',
    width: 266,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 5,
    iconCls: 'icon-status',
    title: 'My Status',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'label',
                    cls: 'availability-indicator-off',
                    itemId: 'agentStateLabel',
                    padding: 2,
                    text: 'Unavailable'
                },
                {
                    xtype: 'button',
                    flex: 0,
                    itemId: 'makeMeAvailableButton',
                    text: 'Make Me Available'
                },
                {
                    xtype: 'dataview',
                    flex: 1,
                    id: 'inbox-stats-view',
                    itemTpl: [
                        '<div id="inbox-stats">',
                        '	<tpl for=".">',
                        '		<div id="inbox-active-value">{activeCount}</div><div id="inbox-active-label">Active Items:</div>',
                        '		<div id="inbox-hold-value">{heldCount}</div><div id="inbox-hold-label">Held Items:</div>',
                        '	</tpl>',
                        '</div>'
                    ],
                    store: 'AuthenticatedAgent'
                }
            ]
        });

        me.callParent(arguments);
    }

});