/*
 * File: app/view/SpmViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Spm.view.SpmViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.spmViewport',

    requires: [
        'Spm.view.HeaderContainer',
        'Spm.view.TabPanel',
        'Spm.view.NavigationPanel',
        'Spm.view.LoginForm'
    ],

    itemId: 'spmViewport',
    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    itemId: 'mainContainer',
                    width: 150,
                    layout: {
                        type: 'border'
                    },
                    items: [
                        {
                            xtype: 'headerContainer',
                            region: 'north'
                        },
                        {
                            xtype: 'tabPanel',
                            region: 'center'
                        },
                        {
                            xtype: 'navigationPanel',
                            region: 'west'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    itemId: 'loginContainer',
                    layout: {
                        align: 'middle',
                        pack: 'center',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'loginForm'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    showLoginDialog: function() {
        this.getLayout().setActiveItem('loginContainer');
    },

    showMainContainer: function() {
        this.getLayout().setActiveItem('mainContainer');
    }

});